version: '3'
services:
  psql-server:
    container_name: 'pg-server'
    image: 'postgres'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
    networks:
      - backend-local-networks
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9000:8080
    networks:
      - backend-local-networks
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=nestjs
      - RABBITMQ_DEFAULT_USER=nestjs
      - RABBITMQ_DEFAULT_PASS=nestjs
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend-local-networks
networks:
  backend-local-networks:
