version: '3.8'
services:
  psql-server:
    container_name: 'pg-server'
    image: 'postgres'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
    networks:
      - backend-local-networks
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9000:8080
    networks:
      - backend-local-networks
networks:
  backend-local-networks:
